# Generated by Django 3.2.6 on 2021-09-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField(db_column='Account')),
                ('password', models.TextField(db_column='Password')),
                ('age', models.TextField(db_column='Age')),
                ('city', models.TextField(db_column='City')),
            ],
            options={
                'db_table': 'django_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.TextField(db_column='Singer')),
                ('song', models.TextField(db_column='Song')),
                ('year', models.TextField(db_column='Year')),
                ('country', models.TextField(db_column='Country')),
                ('click', models.IntegerField(db_column='Click')),
            ],
            options={
                'db_table': 'leaderboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField(db_column='account')),
                ('password', models.TextField(db_column='password')),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
