# Generated by Django 3.2.6 on 2021-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_data', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(default=1, max_length=100, verbose_name='影片檔名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=5000, verbose_name='內容'),
        ),
    ]
