# Generated by Django 3.2.6 on 2021-10-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_data', '0003_auto_20210924_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
