# Generated by Django 3.2.6 on 2021-11-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='標題')),
                ('content', models.CharField(max_length=5000, verbose_name='內容')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
